import React, { useState, useCallback } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import ScoreRing from './ScoreRing';
import SkillChart from './SkillChart';
import WordCloud from './WordCloud';
import StrengthRadar from './StrengthRadar';
import ATSChecker from './ATSChecker';

const TABS = [
  { id: 'overview', label: 'Overview', icon: '📊' },
  { id: 'keywords', label: 'Keywords', icon: '🔑' },
  { id: 'ats', label: 'ATS Check', icon: '🤖' },
  { id: 'suggestions', label: 'Suggestions', icon: '💡' },
  { id: 'readability', label: 'Readability', icon: '📖' },
  { id: 'ai-insights', label: 'AI Insights', icon: '✨' },
];

const panelVariants = {
  initial: { opacity: 0, y: 12 },
  animate: { opacity: 1, y: 0, transition: { duration: 0.35, ease: [0.4, 0, 0.2, 1] } },
  exit: { opacity: 0, y: -8, transition: { duration: 0.2 } },
};

export default function ResultsDashboard({ results, aiResults, resumeText, onDownload, onCopy, onReset }) {
  const [activeTab, setActiveTab] = useState('overview');
  const [copySuccess, setCopySuccess] = useState(false);

  const handleCopy = useCallback(async () => {
    const ok = await onCopy();
    if (ok) {
      setCopySuccess(true);
      setTimeout(() => setCopySuccess(false), 2000);
    }
  }, [onCopy]);

  const { score, breakdown, sections, achievements, actionVerbs, keywordResult, readability, skills, suggestions, jobKeywords } = results;

  return (
    <motion.section
      initial={{ opacity: 0, y: 30 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5, ease: [0.4, 0, 0.2, 1] }}
      className="glass-card-solid p-4 sm:p-6 lg:p-8"
      aria-labelledby="results-heading"
    >
      <h2 id="results-heading" className="text-lg sm:text-xl font-bold text-surface-800 dark:text-surface-100 mb-3 sm:mb-4">
        Analysis Results
      </h2>

      {/* AI disclosure */}
      <div className="bg-blue-50 dark:bg-blue-950/30 border-l-4 border-blue-500 rounded-r-lg px-3 sm:px-4 py-2.5 sm:py-3 mb-4 sm:mb-6">
        <p className="text-[11px] sm:text-xs text-blue-700 dark:text-blue-300">
          Suggestions are generated by heuristic + AI analysis and may not capture all nuances. Use as a starting point.
        </p>
      </div>

      {/* Score Dashboard */}
      <ScoreRing score={score} breakdown={breakdown} />

      {/* Tabs - scrollable on mobile */}
      <div className="relative mt-6 sm:mt-8 mb-4 sm:mb-6">
        <div className="tab-scroll-container flex gap-0.5 sm:gap-1 border-b-2 border-surface-200 dark:border-surface-700 overflow-x-auto pb-0" role="tablist" aria-label="Result categories">
          {TABS.map((tab) => (
            <button
              key={tab.id}
              role="tab"
              aria-selected={activeTab === tab.id}
              aria-controls={`panel-${tab.id}`}
              className={`relative px-2.5 sm:px-4 py-2 sm:py-2.5 text-xs sm:text-sm font-medium whitespace-nowrap -mb-[2px] transition-all duration-200 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-500 rounded-t-lg flex-shrink-0 ${
                activeTab === tab.id
                  ? 'text-brand-600 dark:text-brand-400'
                  : 'text-surface-500 hover:text-surface-700 dark:hover:text-surface-300'
              }`}
              onClick={() => setActiveTab(tab.id)}
            >
              <span className="text-xs mr-0.5 sm:mr-1 hidden xs:inline">{tab.icon}</span>
              <span className="hidden xs:inline">{tab.label}</span>
              <span className="xs:hidden">{tab.icon}</span>
              {activeTab === tab.id && (
                <motion.div
                  layoutId="activeTabIndicator"
                  className="absolute bottom-0 left-0 right-0 h-0.5 bg-brand-500 rounded-full"
                  transition={{ type: 'spring', stiffness: 500, damping: 35 }}
                />
              )}
            </button>
          ))}
        </div>
      </div>

      {/* Tab Panels */}
      <AnimatePresence mode="wait">
        <motion.div
          key={activeTab}
          variants={panelVariants}
          initial="initial"
          animate="animate"
          exit="exit"
        >
          {activeTab === 'overview' && (
            <OverviewPanel sections={sections} readability={readability} achievements={achievements} actionVerbs={actionVerbs} skills={skills} resumeText={resumeText} jobKeywords={jobKeywords} breakdown={breakdown} contactInfo={results.contactInfo} />
          )}
          {activeTab === 'keywords' && (
            <KeywordsPanel keywordResult={keywordResult} skills={skills} jobKeywords={jobKeywords} />
          )}
          {activeTab === 'ats' && (
            <ATSChecker sections={sections} contactInfo={results.contactInfo} readability={readability} skills={skills} keywordResult={keywordResult} />
          )}
          {activeTab === 'suggestions' && (
            <SuggestionsPanel suggestions={suggestions} />
          )}
          {activeTab === 'readability' && (
            <ReadabilityPanel readability={readability} />
          )}
          {activeTab === 'ai-insights' && (
            <AIInsightsPanel aiResults={aiResults} />
          )}
        </motion.div>
      </AnimatePresence>

      {/* Export actions */}
      <div className="flex flex-col xs:flex-row flex-wrap gap-2 sm:gap-3 mt-6 sm:mt-8 pt-4 sm:pt-6 border-t border-surface-200 dark:border-surface-700">
        <motion.button whileHover={{ scale: 1.03 }} whileTap={{ scale: 0.97 }} onClick={onDownload} className="btn-secondary text-xs sm:text-sm" aria-label="Download analysis report">
          <svg width="14" height="14" viewBox="0 0 16 16" aria-hidden="true" className="sm:w-4 sm:h-4">
            <path d="M8 2v9M4 8l4 4 4-4" stroke="currentColor" strokeWidth="1.5" fill="none" strokeLinecap="round" strokeLinejoin="round"/>
            <path d="M2 12v1a1 1 0 001 1h10a1 1 0 001-1v-1" stroke="currentColor" strokeWidth="1.5" fill="none" strokeLinecap="round"/>
          </svg>
          Download Report
        </motion.button>
        <motion.button whileHover={{ scale: 1.03 }} whileTap={{ scale: 0.97 }} onClick={handleCopy} className="btn-secondary text-xs sm:text-sm" aria-label="Copy suggestions to clipboard">
          <svg width="14" height="14" viewBox="0 0 16 16" aria-hidden="true" className="sm:w-4 sm:h-4">
            <rect x="5" y="5" width="9" height="9" rx="1" stroke="currentColor" strokeWidth="1.5" fill="none"/>
            <path d="M11 3H4a1 1 0 00-1 1v7" stroke="currentColor" strokeWidth="1.5" fill="none" strokeLinecap="round"/>
          </svg>
          {copySuccess ? '✓ Copied!' : 'Copy'}
        </motion.button>
        <motion.button whileHover={{ scale: 1.03 }} whileTap={{ scale: 0.97 }} onClick={onReset} className="btn-ghost text-xs sm:text-sm xs:ml-auto" aria-label="Clear all inputs and results">
          Reset
        </motion.button>
      </div>
    </motion.section>
  );
}

// ── Overview Panel ──
function OverviewPanel({ sections, readability, achievements, actionVerbs, skills, resumeText, jobKeywords, breakdown, contactInfo }) {
  const stats = [
    { value: readability.wordCount.toLocaleString(), label: 'Words', icon: '📝' },
    { value: readability.sentenceCount, label: 'Sentences', icon: '📎' },
    { value: readability.bullets, label: 'Bullets', icon: '•' },
    { value: achievements.length, label: 'Metrics', icon: '📊' },
    { value: actionVerbs.strong.length, label: 'Verbs', icon: '⚡' },
    { value: skills.length, label: 'Skills', icon: '🎯' },
  ];

  return (
    <div className="space-y-5 sm:space-y-6">
      <div>
        <h3 className="text-xs sm:text-sm font-bold text-surface-700 dark:text-surface-200 mb-2 sm:mb-3">Detected Sections</h3>
        <div className="grid grid-cols-2 sm:grid-cols-3 gap-1.5 sm:gap-2">
          {Object.entries(sections).map(([name, found], i) => (
            <motion.div
              key={name}
              initial={{ opacity: 0, x: -10 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ delay: i * 0.04, duration: 0.3 }}
              whileHover={{ scale: 1.03, y: -1 }}
              className={`flex items-center gap-1.5 sm:gap-2 px-2 sm:px-3 py-2 sm:py-2.5 rounded-lg sm:rounded-xl text-xs sm:text-sm font-medium cursor-default transition-shadow duration-200 ${
                found
                  ? 'bg-emerald-50 dark:bg-emerald-950/30 text-emerald-700 dark:text-emerald-400 hover:shadow-md hover:shadow-emerald-500/10'
                  : 'bg-red-50 dark:bg-red-950/30 text-red-600 dark:text-red-400 hover:shadow-md hover:shadow-red-500/10'
              }`}
            >
              <span className="text-xs sm:text-base">{found ? '✓' : '✗'}</span>
              <span className="truncate">{name}</span>
            </motion.div>
          ))}
        </div>
      </div>

      <div>
        <h3 className="text-xs sm:text-sm font-bold text-surface-700 dark:text-surface-200 mb-2 sm:mb-3">Quick Stats</h3>
        <div className="grid grid-cols-3 sm:grid-cols-6 gap-1.5 sm:gap-2">
          {stats.map((s, i) => (
            <motion.div
              key={s.label}
              initial={{ scale: 0.8, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              transition={{ delay: i * 0.06, duration: 0.35, ease: [0.22, 1, 0.36, 1] }}
              whileHover={{ scale: 1.08, y: -3 }}
              className="text-center p-2 sm:p-3 bg-surface-50 dark:bg-surface-900/40 rounded-lg sm:rounded-xl cursor-default hover:shadow-lg hover:shadow-brand-500/[0.06] transition-shadow duration-300 group"
            >
              <div className="text-lg sm:text-xl font-black text-brand-600 dark:text-brand-400 group-hover:scale-110 transition-transform duration-200">{s.value}</div>
              <div className="text-[9px] sm:text-[10px] text-surface-500 dark:text-surface-400 mt-0.5">{s.label}</div>
            </motion.div>
          ))}
        </div>
      </div>

      {/* Strength Radar */}
      <StrengthRadar
        breakdown={breakdown}
        sections={sections}
        readability={readability}
        contactInfo={contactInfo}
        achievements={achievements}
        actionVerbs={actionVerbs}
      />

      {/* Skill distribution chart */}
      {skills.length > 0 && (
        <motion.div
          initial={{ opacity: 0, y: 15 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.3, duration: 0.4 }}
        >
          <h3 className="text-xs sm:text-sm font-bold text-surface-700 dark:text-surface-200 mb-2 sm:mb-3">Skill Distribution</h3>
          <SkillChart skills={skills} />
        </motion.div>
      )}

      {/* Word Cloud */}
      <WordCloud text={resumeText} jobKeywords={jobKeywords} />
    </div>
  );
}

// ── Keywords Panel ──
function KeywordsPanel({ keywordResult, skills, jobKeywords }) {
  return (
    <div>
      <h3 className="text-xs sm:text-sm font-bold text-surface-700 dark:text-surface-200 mb-2 sm:mb-3">Keyword Match</h3>

      {jobKeywords.length === 0 ? (
        <p className="text-xs sm:text-sm text-surface-500 dark:text-surface-400 bg-surface-50 dark:bg-surface-900/30 rounded-xl p-3 sm:p-4">
          Paste a job description or select a role to see keyword matching.
        </p>
      ) : (
        <>
          {/* Match bar */}
          <div className="flex items-center gap-2 sm:gap-3 mb-3 sm:mb-4">
            <span className="text-xs sm:text-sm text-surface-500 w-16 sm:w-24">Match Rate</span>
            <div className="flex-1 h-5 sm:h-6 bg-surface-200 dark:bg-surface-700 rounded-full overflow-hidden relative">
              <motion.div
                className="h-full rounded-full flex items-center justify-end pr-2 sm:pr-3"
                style={{
                  backgroundColor: keywordResult.score >= 70 ? '#10b981' : keywordResult.score >= 40 ? '#f59e0b' : '#ef4444',
                }}
                initial={{ width: 0 }}
                animate={{ width: `${Math.max(keywordResult.score, 8)}%` }}
                transition={{ duration: 0.8, ease: 'easeOut' }}
              >
                <span className="text-[10px] sm:text-xs font-bold text-white">{keywordResult.score}%</span>
              </motion.div>
            </div>
          </div>
          <p className="text-[10px] sm:text-xs text-surface-500 mb-3 sm:mb-4">
            Matched {keywordResult.matched.length} of {jobKeywords.length} keywords
          </p>
        </>
      )}

      <h3 className="text-xs sm:text-sm font-bold text-surface-700 dark:text-surface-200 mb-2 sm:mb-3 mt-4 sm:mt-6">Extracted Skills</h3>
      {skills.length === 0 ? (
        <p className="text-xs sm:text-sm text-surface-500 dark:text-surface-400">No technical skills detected.</p>
      ) : (
        <div className="flex flex-wrap gap-1.5 sm:gap-2">
          {skills.map((skill, i) => {
            const isMatched = jobKeywords.some((kw) => kw.includes(skill) || skill.includes(kw));
            return (
              <motion.span
                key={skill}
                initial={{ opacity: 0, scale: 0.8 }}
                animate={{ opacity: 1, scale: 1 }}
                transition={{ delay: i * 0.03, duration: 0.25 }}
                whileHover={{ scale: 1.1, y: -2 }}
                className={`tag-pill cursor-default text-[10px] sm:text-xs ${
                  isMatched
                    ? 'bg-emerald-50 dark:bg-emerald-950/30 text-emerald-700 dark:text-emerald-400 ring-1 ring-emerald-200 dark:ring-emerald-800 hover:shadow-md hover:shadow-emerald-500/10'
                    : 'bg-blue-50 dark:bg-blue-950/30 text-blue-600 dark:text-blue-400 ring-1 ring-blue-200 dark:ring-blue-800 hover:shadow-md hover:shadow-blue-500/10'
                }`}
              >
                {skill}
              </motion.span>
            );
          })}
        </div>
      )}

      {keywordResult.missing && keywordResult.missing.length > 0 && (
        <>
          <h3 className="text-xs sm:text-sm font-bold text-surface-700 dark:text-surface-200 mb-2 sm:mb-3 mt-4 sm:mt-6">Missing Keywords</h3>
          <div className="flex flex-wrap gap-1.5 sm:gap-2">
            {keywordResult.missing.slice(0, 15).map((kw) => (
              <span
                key={kw}
                className="tag-pill text-[10px] sm:text-xs bg-surface-100 dark:bg-surface-800 text-surface-500 dark:text-surface-400 ring-1 ring-surface-200 dark:ring-surface-700"
              >
                {kw}
              </span>
            ))}
          </div>
        </>
      )}
    </div>
  );
}

// ── Suggestions Panel ──
function SuggestionsPanel({ suggestions }) {
  const priorityConfig = {
    high: { label: 'High Priority', color: 'text-red-600 dark:text-red-400', bg: 'bg-red-50 dark:bg-red-950/20', border: 'border-l-red-500' },
    medium: { label: 'Suggestion', color: 'text-amber-600 dark:text-amber-400', bg: 'bg-amber-50 dark:bg-amber-950/20', border: 'border-l-amber-500' },
    low: { label: 'Nice to Have', color: 'text-blue-600 dark:text-blue-400', bg: 'bg-blue-50 dark:bg-blue-950/20', border: 'border-l-blue-500' },
    positive: { label: 'Strength', color: 'text-emerald-600 dark:text-emerald-400', bg: 'bg-emerald-50 dark:bg-emerald-950/20', border: 'border-l-emerald-500' },
  };

  if (suggestions.length === 0) {
    return <p className="text-xs sm:text-sm text-surface-500">No specific suggestions — your resume looks solid.</p>;
  }

  return (
    <div className="space-y-2 sm:space-y-3">
      {suggestions.map((s, i) => {
        const config = priorityConfig[s.priority] || priorityConfig.medium;
        return (
          <motion.div
            key={i}
            initial={{ opacity: 0, x: -10 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ delay: i * 0.05 }}
            className={`${config.bg} border-l-4 ${config.border} rounded-r-lg sm:rounded-r-xl p-3 sm:p-4`}
          >
            <div className={`text-[9px] sm:text-[10px] font-bold uppercase tracking-wider ${config.color} mb-1`}>
              {config.label}
            </div>
            <div className="text-xs sm:text-sm font-semibold text-surface-800 dark:text-surface-100 mb-1">{s.text}</div>
            <div className="text-[11px] sm:text-xs text-surface-600 dark:text-surface-400 leading-relaxed">{s.detail}</div>
          </motion.div>
        );
      })}
    </div>
  );
}

// ── Readability Panel ──
function ReadabilityPanel({ readability }) {
  const gaugeColor = readability.level === 'good' ? '#10b981' : readability.level === 'ok' ? '#f59e0b' : '#ef4444';
  const radius = 32;
  const circumference = 2 * Math.PI * radius;
  const offset = circumference * (1 - readability.fleschEase / 100);

  const metrics = [
    { label: 'Grade Level', value: `Grade ${readability.gradeLevel}` },
    { label: 'Avg Words/Sent.', value: readability.avgWordsPerSentence },
    { label: 'Complex Words', value: `${readability.complexPercent}%` },
    { label: 'Paragraphs', value: readability.paragraphs },
    { label: 'Word Count', value: readability.wordCount.toLocaleString() },
    { label: 'Sentences', value: readability.sentenceCount },
  ];

  return (
    <div>
      <div className="flex flex-col sm:flex-row items-center gap-4 sm:gap-6 mb-4 sm:mb-6">
        <svg className="w-20 h-20 sm:w-24 sm:h-24 flex-shrink-0" viewBox="0 0 80 80" aria-hidden="true">
          <circle cx="40" cy="40" r={radius} strokeWidth="8" fill="none" className="stroke-surface-200 dark:stroke-surface-700" />
          <motion.circle
            cx="40" cy="40" r={radius} strokeWidth="8" fill="none"
            stroke={gaugeColor}
            strokeDasharray={circumference}
            strokeLinecap="round"
            transform="rotate(-90 40 40)"
            initial={{ strokeDashoffset: circumference }}
            animate={{ strokeDashoffset: offset }}
            transition={{ duration: 1, ease: 'easeOut' }}
          />
          <text x="40" y="38" textAnchor="middle" fontSize="16" fontWeight="bold" fill={gaugeColor}>{readability.fleschEase}</text>
          <text x="40" y="52" textAnchor="middle" fontSize="8" className="fill-surface-400">/ 100</text>
        </svg>
        <div className="text-center sm:text-left">
          <h4 className="text-sm sm:text-base font-bold text-surface-800 dark:text-surface-100">
            Flesch Reading Ease: {readability.fleschEase}/100
          </h4>
          <p className="text-xs sm:text-sm text-surface-500 mt-1">{readability.description}</p>
        </div>
      </div>

      <div className="grid grid-cols-2 sm:grid-cols-3 gap-2 sm:gap-3">
        {metrics.map((m, i) => (
          <motion.div
            key={m.label}
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: i * 0.06, duration: 0.3 }}
            whileHover={{ scale: 1.05, y: -2 }}
            className="bg-surface-50 dark:bg-surface-900/40 rounded-lg sm:rounded-xl p-2.5 sm:p-3 text-center cursor-default hover:shadow-md transition-shadow duration-200"
          >
            <div className="text-[10px] sm:text-xs text-surface-500 dark:text-surface-400 mb-0.5 sm:mb-1">{m.label}</div>
            <div className="text-base sm:text-lg font-bold text-surface-800 dark:text-surface-100">{m.value}</div>
          </motion.div>
        ))}
      </div>
    </div>
  );
}

// ── AI Insights Panel ──
function AIInsightsPanel({ aiResults }) {
  if (!aiResults) {
    return (
      <div className="text-center py-6 sm:py-8">
        <div className="w-14 h-14 sm:w-16 sm:h-16 mx-auto mb-3 sm:mb-4 rounded-2xl bg-surface-100 dark:bg-surface-800 flex items-center justify-center">
          <svg width="24" height="24" viewBox="0 0 24 24" fill="none" className="text-surface-400 sm:w-7 sm:h-7">
            <path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm-2 15l-5-5 1.41-1.41L10 14.17l7.59-7.59L19 8l-9 9z" fill="currentColor"/>
          </svg>
        </div>
        <h3 className="text-xs sm:text-sm font-bold text-surface-700 dark:text-surface-200 mb-1.5 sm:mb-2">No AI Analysis Available</h3>
        <p className="text-[11px] sm:text-xs text-surface-500 dark:text-surface-400 max-w-sm mx-auto">
          Add a Gemini or OpenAI API key in your <code className="px-1 sm:px-1.5 py-0.5 bg-surface-100 dark:bg-surface-800 rounded text-brand-600 dark:text-brand-400">.env</code> file to enable AI-powered insights.
        </p>
      </div>
    );
  }

  return (
    <div className="space-y-4 sm:space-y-6">
      {/* Summary */}
      {aiResults.summary && (
        <div>
          <h3 className="text-xs sm:text-sm font-bold text-surface-700 dark:text-surface-200 mb-2">AI Summary</h3>
          <p className="text-xs sm:text-sm text-surface-600 dark:text-surface-300 leading-relaxed bg-surface-50 dark:bg-surface-900/30 rounded-xl p-3 sm:p-4">
            {aiResults.summary}
          </p>
        </div>
      )}

      {/* Strengths */}
      {aiResults.strengths?.length > 0 && (
        <div>
          <h3 className="text-xs sm:text-sm font-bold text-surface-700 dark:text-surface-200 mb-2">✨ Strengths</h3>
          <ul className="space-y-1.5 sm:space-y-2">
            {aiResults.strengths.map((s, i) => (
              <li key={i} className="text-xs sm:text-sm text-surface-600 dark:text-surface-300 flex gap-2 bg-emerald-50 dark:bg-emerald-950/20 rounded-lg p-2.5 sm:p-3">
                <span className="text-emerald-500 font-bold flex-shrink-0">•</span>
                {s}
              </li>
            ))}
          </ul>
        </div>
      )}

      {/* Weaknesses */}
      {aiResults.weaknesses?.length > 0 && (
        <div>
          <h3 className="text-xs sm:text-sm font-bold text-surface-700 dark:text-surface-200 mb-2">⚠ Areas to Improve</h3>
          <ul className="space-y-1.5 sm:space-y-2">
            {aiResults.weaknesses.map((w, i) => (
              <li key={i} className="text-xs sm:text-sm text-surface-600 dark:text-surface-300 flex gap-2 bg-amber-50 dark:bg-amber-950/20 rounded-lg p-2.5 sm:p-3">
                <span className="text-amber-500 font-bold flex-shrink-0">•</span>
                {w}
              </li>
            ))}
          </ul>
        </div>
      )}

      {/* AI-suggested improvements */}
      {aiResults.improvements?.length > 0 && (
        <div>
          <h3 className="text-xs sm:text-sm font-bold text-surface-700 dark:text-surface-200 mb-2">🎯 Detailed Improvements</h3>
          <div className="space-y-1.5 sm:space-y-2">
            {aiResults.improvements.map((imp, i) => (
              <div key={i} className="bg-surface-50 dark:bg-surface-900/30 rounded-lg sm:rounded-xl p-3 sm:p-4">
                <div className="flex items-center gap-2 mb-1">
                  <span className={`text-[9px] sm:text-[10px] font-bold uppercase tracking-wider ${
                    imp.priority === 'high' ? 'text-red-500' : imp.priority === 'medium' ? 'text-amber-500' : 'text-blue-500'
                  }`}>
                    {imp.priority}
                  </span>
                  <span className="text-xs sm:text-sm font-semibold text-surface-700 dark:text-surface-200">{imp.area}</span>
                </div>
                <p className="text-[11px] sm:text-xs text-surface-600 dark:text-surface-400">{imp.suggestion}</p>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Job match analysis */}
      {aiResults.jobMatchScore !== undefined && (
        <div>
          <h3 className="text-xs sm:text-sm font-bold text-surface-700 dark:text-surface-200 mb-2">🔄 Job Match</h3>
          <div className="bg-surface-50 dark:bg-surface-900/30 rounded-xl p-3 sm:p-4">
            <div className="flex items-center gap-3 mb-2 sm:mb-3">
              <span className="text-xl sm:text-2xl font-black text-brand-600 dark:text-brand-400">{aiResults.jobMatchScore}%</span>
              <span className="text-xs sm:text-sm text-surface-500">Job Description Match</span>
            </div>
            {aiResults.matchAnalysis && (
              <p className="text-[11px] sm:text-xs text-surface-600 dark:text-surface-400 mb-2 sm:mb-3">{aiResults.matchAnalysis}</p>
            )}
            {aiResults.missingSkills?.length > 0 && (
              <div>
                <span className="text-[10px] sm:text-xs font-bold text-surface-500 mb-1.5 sm:mb-2 block">Missing Skills:</span>
                <div className="flex flex-wrap gap-1 sm:gap-1.5">
                  {aiResults.missingSkills.map((s, i) => (
                    <span key={i} className="tag-pill text-[10px] sm:text-xs bg-red-50 dark:bg-red-950/20 text-red-600 dark:text-red-400 ring-1 ring-red-200 dark:ring-red-800">
                      {s}
                    </span>
                  ))}
                </div>
              </div>
            )}
          </div>
        </div>
      )}

      {/* Extracted data */}
      {aiResults.extractedData && (
        <div>
          <h3 className="text-xs sm:text-sm font-bold text-surface-700 dark:text-surface-200 mb-2">📋 Extracted Data</h3>
          <div className="space-y-2 sm:space-y-3">
            {aiResults.extractedData.name && (
              <div className="bg-surface-50 dark:bg-surface-900/30 rounded-xl p-2.5 sm:p-3">
                <span className="text-[10px] sm:text-xs text-surface-500 block mb-0.5 sm:mb-1">Name</span>
                <span className="text-xs sm:text-sm font-semibold text-surface-800 dark:text-surface-100">{aiResults.extractedData.name}</span>
              </div>
            )}

            {aiResults.extractedData.experience?.length > 0 && (
              <div className="bg-surface-50 dark:bg-surface-900/30 rounded-xl p-2.5 sm:p-3">
                <span className="text-[10px] sm:text-xs text-surface-500 block mb-1.5 sm:mb-2">Experience</span>
                {aiResults.extractedData.experience.map((exp, i) => (
                  <div key={i} className="mb-1.5 last:mb-0">
                    <span className="text-xs sm:text-sm font-semibold text-surface-800 dark:text-surface-100">{exp.title}</span>
                    <span className="text-[10px] sm:text-xs text-surface-500 ml-1 sm:ml-2">{exp.company} • {exp.duration}</span>
                  </div>
                ))}
              </div>
            )}

            {aiResults.extractedData.education?.length > 0 && (
              <div className="bg-surface-50 dark:bg-surface-900/30 rounded-xl p-2.5 sm:p-3">
                <span className="text-[10px] sm:text-xs text-surface-500 block mb-1.5 sm:mb-2">Education</span>
                {aiResults.extractedData.education.map((edu, i) => (
                  <div key={i} className="mb-1.5 last:mb-0">
                    <span className="text-xs sm:text-sm font-semibold text-surface-800 dark:text-surface-100">{edu.degree}</span>
                    <span className="text-[10px] sm:text-xs text-surface-500 ml-1 sm:ml-2">{edu.institution} • {edu.year}</span>
                  </div>
                ))}
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
}
